### ISSUE TITLE
Where is the hidden file？

### ISSUE THREAD

**Issue by sophiabigtree** [daniellerch/aletheia#1]
Hello~I'm a newcomer into Image steganalysis. When I use the command like"./aletheia.py hill-sim bossbase 0.40 bossbase_hill040 ".I got a question：What file is hidden in the image?Could you please  explain it in detail?Thanks a lot in advance.

**Comment by daniellerch** [comment]
There is no hidden file. You are hiding random information using the HILL simulator. This is not a steganography tool, so there is enough with a simulator for steganalysis tasks.
