### ISSUE TITLE
HELP: Running ALASKA2 model

### ISSUE THREAD

**Issue by OmarAlmighty** [daniellerch/aletheia#11]
I tried running _effnetb0-A-alaska2-steghide.h5_ model from the terminal on 6 stego images to test my own embedding alogrithm, the output is all 0.0 except for the last image is 0.002.

But running the same model on the same stego images manually by writing the code for loading the h5 model outputs different values. Here is my code:

```
def decode_image(filename, image_size=(512, 512)):
    bits = tf.io.read_file(filename)
    image = tf.image.decode_jpeg(bits, channels=3)
    image = tf.cast(image, tf.float32) / 255.0
    image = tf.image.resize(image, image_size)
    image = tf.expand_dims(image, axis=0)
    return image


model = keras.models.load_model("models/effnetb0-A-alaska2-steghide.h5")

imgs = []
for i in range(6):
    name = "test/n/st"+str(i)+".jpg"
    i = decode_image(name)
    x = model.predict(i,10)
    print(name, ":", x)
```

The output is: 
test/n/st0.jpg : **tf.Tensor([[9.9900407e-01 9.9591375e-04]]**, shape=(1, 2), dtype=float32)
test/n/st1.jpg : **tf.Tensor([[9.990381e-01 9.619216e-04]]**, shape=(1, 2), dtype=float32)
test/n/st2.jpg : **tf.Tensor([[9.9926895e-01 7.3103642e-04]]**, shape=(1, 2), dtype=float32)
test/n/st3.jpg : **tf.Tensor([[9.9925345e-01 7.4653851e-04]]**, shape=(1, 2), dtype=float32)
test/n/st4.jpg : **tf.Tensor([[0.9975908  0.00240928]]**, shape=(1, 2), dtype=float32)
test/n/st5.jpg : **tf.Tensor([[0.8278996  0.17210042]]**, shape=(1, 2), dtype=float32)

Why the output is different in both cases, and what does the first and second values in the second output mean?

**Comment by daniellerch** [comment]
The two values are the probability of being cover and the probability of being stego, respectively. The output of Aletheia is the rounded stego probability. For example, in the first case is 9.9591375e-04. If we round this value with 3 decimals the result is 0.001.

**Comment by OmarAlmighty** [comment]
@daniellerch Thanks
