### ISSUE TITLE
PermissionError: [WinError 32] & Slow Classification with GPU

### ISSUE THREAD

**Issue by FaiZaman** [daniellerch/aletheia#12]
I've had two issues with aletheia when I run the following command on Windows 10:

```
> python aletheia.py e4s-predict models/e4s_srm_bossbase_lsbm0.10_gs.model srm sample_images/1_lsb.pgm
```

My first issue is that the program crashes at line 153, in `aletheia/octave_interface.py` at the line:

```shutil.rmtree(tmpdir)```

with the error:

```
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\faiz\\AppData\\Local\\Temp\\tmpnk6riay9'
```

I commented out the line in question and it appears to work, but my folder keeps filling up with temp files because they're not being deleted, which is slightly inconvenient. Is there a better fix for this or is the issue to do with Windows?

The second issue is more of a confirmation - upon running the aforementioned command, it takes about 40 seconds to classify an image as a Cover or Stego image using both my CPU and my GPU. After further investigation it looks like the bulk of this time is spent initialising the SRM also in `aletheia/octave_interface.py` at line 150:

```status = p.wait()```

I just wanted to confirm whether it's supposed to take this long? If so, I'll have to readjust the number of images I use in my evaluation because it would take too long to run this for all 10,000 images in the BOSSbase dataset. If not, is there something I've missed?

Also, please tell me if I'm supposed to create two separate issues for this - if so I'll edit this one and create a new one for my second issue (it's my first time creating an issue on GitHub!)

**Comment by daniellerch** [comment]
The command that you are using needs to perform a feature extraction of the image using Spatial Rich Models, before classification. This is very slow. I suggest you to use effnetb0 models. It's faster and more accurate.

Please, open a new issue for the Windows question.

**Comment by FaiZaman** [comment]
Thanks for the information - could you please give me an example command using an effnetb0 model?

**Comment by FaiZaman** [comment]
I've attempted to run the effnetb0 model on my images with this command:

```
> python aletheia.py effnetb0-predict sample_images models/effnetb0-A-alaska2-nsf5.h5 0
```

where I tried all the effnetb0 models, but for all of them I got the same error:

```
WARNING: image ignored: sample_images\1_lsb.pgm , expected number of channels: 3
```

It appears that this is because the effnetb0 models only work on colour images since they were trained on the ALASKA2 dataset. If I wanted to test the effnetb0 models on the BOSSbase dataset which is greyscale, how would I go about doing this? Is there a pretrained model I overlooked or would I need to train the effnetb0 model on the BOSSbase dataset myself?

**Comment by daniellerch** [comment]
The efficient net models work with three channels so you can't use them with grayscale images. By the other side, in steganalysis, if you use a model trained in one database with images from another database you are at risk of Cover Source Mismatch. I'm preparing DCI models for this, but they are not ready yet.

**Comment by FaiZaman** [comment]
In that case, I may switch my embedding method to produce colour images so that I can run these models on my stego images produced from the ALASKA2 dataset.

Additionally, the output for a colour image with efficientnet is the following:

```
sample_images\lena.jpg 0.554
sample_images\lena.png 0.934
sample_images\lena_ebs_0.20.jpg 0.733
sample_images\lena_ebs_0.30.jpg 0.781
sample_images\lena_ebs_0.40.jpg 0.788
sample_images\lena_ebs_0.50.jpg 0.933
sample_images\lena_ebs_0.75.jpg 0.788
sample_images\lena_ebs_1.00.jpg 0.996
...
```

What do the float values (0.554, 0.934, ...) mean? Are they probabilities of the image being cover or stego or are they a different metric?

**Comment by daniellerch** [comment]
This is the probability that the steganographic algorithm corresponding to the model was used.
