### ISSUE TITLE
PermissionError: [WinError32]

### ISSUE THREAD

**Issue by FaiZaman** [daniellerch/aletheia#13]
I run into an issue when I run the following command:

```
> python aletheia.py e4s-predict models/e4s_srm_bossbase_lsbm0.10_gs.model srm sample_images/1_lsb.pgm
```

The program crashes in `aletheia/octave_interface.py` at line 153:

```shutil.rmtree(tmpdir)```

with the error:

```
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\faiz\\AppData\\Local\\Temp\\tmpnk6riay9'
```

I commented out the line in question and it appears to work, but my folder keeps filling up with temp files because they're not being deleted, which is slightly inconvenient. Is there a better fix for this or is the issue to do with Windows?

**Comment by OmarAlmighty** [comment]
I had the same problem. I think it's a problem with the installation of octave libraries.
I solved this by installing Ubuntu on a VM and following all the installation steps provided [here](https://github.com/daniellerch/aletheia/blob/master/doc/INSTALL.md)
