### ISSUE TITLE
Feature request: run e4s-predict on GPU

### ISSUE THREAD

**Issue by pfeatherstone** [daniellerch/aletheia#14]
It looks like a lot of original algorithms are implemented in octave. How much effort would it be to translate to cupy or pytorch to run the algorithms on GPU?
This would be an awesome feature.

**Comment by daniellerch** [comment]
I guess a lot of effort. Many researchers implement their papers using Matlab. I have translated some of then into Python, but there is a lot of work to do. By the other side, the e4s classifier is not so accurate as deep learning, so in this case I do not plan to implement it in Python.

**Comment by pfeatherstone** [comment]
I've found that the pretrained models for e4s work pretty well whereas the pretrained weights for efficientnetb0 are overfitted to your datasets.
