### ISSUE TITLE
Question: Alaska2 dataset

### ISSUE THREAD

**Issue by pfeatherstone** [daniellerch/aletheia#16]
Hi there. When training the efficientnet_b0 models, you mention that they are trained on the ALASKA2 dataset. Upon investigating the kaggle page, it looks like the steganography models used to generate the dataset are ```JMiPOD```, ```JUNIWARD``` and ```UERD```. However the checkpoints provided by aletheia reference ```lsbr```, ```lsbm```, ```steghide```, ```nsf5``` and ```outguess```. I can't reconcile the model names with the ALASKA2 description. Can you explain? Thanks

**Comment by daniellerch** [comment]
The tools used for hiding information in the Alaska2 contests are not publicly available. So I'm using the Alaska2 cover images for generating my own training sets. By the other side, I'm more interested in detecting methods that are being used in the real world like Steghide, F5 or LSM replacement. In the future I plan to implement my own versions of other unpublished algorithms.

**Comment by pfeatherstone** [comment]
thank you
