### ISSUE TITLE
ModuleNotFoundError: No module named 'efficientnet'

### ISSUE THREAD

**Issue by codeflakes0** [daniellerch/aletheia#18]
when running "aletheia.py auto test.jpg" I get this error:

file "/home/work/.local/lib/python3.7/site-packages/aletheialib/models.py", line 269, in <module>
    import efficientnet.tfkeras as efn
ModuleNotFoundError: No module named 'efficientnet'

I have the same error on Debian 9 + Python 3.9 and Debian 10 + Python 3.7
Installation seems to have work properly

**Comment by daniellerch** [comment]
"efficientnet" package added to requirements.txt.

Thanks.
