### ISSUE TITLE
ValueError: Did not fully consume compressed contents of an miCOMPRESSED element. This can indicate that the .mat file is corrupted.

### ISSUE THREAD

**Issue by qxiaomay** [daniellerch/aletheia#2]
I'm going to build a detector for the HILL algorithm with payload 0.40. 
When I try to hide images with the follow command,
`$ ./aletheia.py hill-sim bossbase 0.40 bossbase_hill040 `
there is an error at the eighth epoch.

`ValueError: Did not fully consume compressed contents of an miCOMPRESSED element. This can indicate that the .mat file is `corrupted.`

![184c929aeac680a55fe4d5ddd2ff6e4](https://user-images.githubusercontent.com/24953690/54522509-62a7ac80-49a8-11e9-8f43-5a63dbcab547.png)

**Comment by daniellerch** [comment]
Error handled in current version. Thanks for reporting.
