### ISSUE TITLE
how to extract the data found in:

### ISSUE THREAD

**Issue by Kratoshate** [daniellerch/aletheia#20]
sorry, What is this useful to me, how to extract the data found in:
python3 aletheia.py sp 0rgb.png
Hidden data found in channel R 0.07434049523415331
Hidden data found in channel G 0.07434049523415331
Hidden data found in channel B 0.07434049523415331

What do these digits mean, is it just an average?

**Comment by daniellerch** [comment]
Aletheia is a detection tool. You can not use it to extract the message.
In fact, you should use the tool that was used to hide the message.
