### ISSUE TITLE
CMake Error: The source directory "/mnt/c/aletheia-master/aletheia" does not appear to contain CMakeLists.txt.

### ISSUE THREAD

**Issue by sana26834** [daniellerch/aletheia#22]
can you provide this file

**Comment by daniellerch** [comment]
Thank you for your interest in the project. The software is primarily written in Python, so there's no need for a CMakeLists.txt file for the main project. The only components that require compiling are the Octave plugins, and they also don't require this file. Could you please let me know what steps you took that led to this error message? It will help me understand your use case better.

For installation and usage guidelines, please refer to the README.

**Comment by daniellerch** [comment]
Closing this issue due to prolonged inactivity. Feel free to reopen if needed. Thanks!
