### ISSUE TITLE
wrong run: $ ./aletheia.py hill-sim bossbase 0.40 bossbase_hill040 

### ISSUE THREAD

**Issue by henryccl** [daniellerch/aletheia#3]
Hello, I'm a green hand. It occurred mistakes when I using this command  $ ./aletheia.py hill-sim bossbase 0.40 bossbase_hill040 . These mistakes are as follows.

/home/hynu/anaconda3/envs/aletheia/lib/python3.5/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
Using 6 threads
Error, retry!
Error, retry!
Error, retry!
'arr' does not have a suitable array shape for any mode.

What should I do ?

**Comment by OrangeIUH** [comment]
I solve it by install octave and octave-image ,octave-signal.

**Comment by daniellerch** [comment]
Great!
