### ISSUE TITLE
incorrect use of word "bitmaps"

### ISSUE THREAD

**Issue by YassineYousfi** [daniellerch/aletheia#30]
(From https://github.com/openjournals/joss-reviews/issues/5982)

In https://github.com/daniellerch/aletheia/blob/master/README.md/ and https://github.com/daniellerch/aletheia/blob/master/aletheia-models/README.md
I'm assuming this means uncompressed images?

**Comment by daniellerch** [comment]
Yes, the term "bitmap" in the documentation indeed refers to uncompressed images. To avoid any confusion, I have updated the documentation to clearly reflect this. Your input is greatly appreciated.
