### ISSUE TITLE
detection thresholds should not be hard coded

### ISSUE THREAD

**Issue by YassineYousfi** [daniellerch/aletheia#32]
(From https://github.com/openjournals/joss-reviews/issues/5982)

in https://github.com/daniellerch/aletheia/blob/master/aletheialib/options/structural.py#L43 for example, if the user wants to detect a payload lower than 0.05 bpp.

**Comment by daniellerch** [comment]
I have implemented the change. Now threshold the threshold can be specified by the user. 
Thank you for the note.
