### ISSUE TITLE
Inconsistency in the number of layers when loading weights from a file

### ISSUE THREAD

**Issue by vasia1247** [daniellerch/aletheia#35]
What could be the problem when working with the "auto" module?

The model was expecting 1 layer, I found two saved ones, what should I do, I’m attaching a screenshot?

![Screenshot from 2024-04-18 12-13-15](https://github.com/daniellerch/aletheia/assets/160625049/78c715aa-c3b4-4051-9718-b5c3f07e4566)

**Comment by Th3Tr1ckst3r** [comment]
I'm having the same issue as well, so its not necessarily just you, or your system. I'm not even using a different image, even running the sample images in auto results in the same issue.

```
bash-5.2$ python3 aletheia.py  auto sample_images/alaska2jpg
'dev' not provided, using: CPU
Running with CPU. It could be very slow!
Traceback (most recent call last):
  File "/home/th3tr1ckst3r/Desktop/aletheia-master/aletheia.py", line 285, in <module>
    main()
  File "/home/th3tr1ckst3r/Desktop/aletheia-master/aletheia.py", line 47, in main
    options.auto.auto()
  File "/home/th3tr1ckst3r/Desktop/aletheia-master/aletheialib/options/auto.py", line 86, in auto
    nn = load_model(nn, "effnetb0-A-alaska2-outguess")
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/th3tr1ckst3r/Desktop/aletheia-master/aletheialib/options/auto.py", line 31, in load_model
    nn.load_model(model_path, quiet=True)
  File "/home/th3tr1ckst3r/Desktop/aletheia-master/aletheialib/models.py", line 403, in load_model
    self.model.load_weights(model_path)
  File "/home/th3tr1ckst3r/.local/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py", line 122, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/th3tr1ckst3r/.local/lib/python3.11/site-packages/keras/src/legacy/saving/legacy_h5_format.py", line 357, in load_weights_from_hdf5_group
    raise ValueError(
ValueError: Layer count mismatch when loading weights from file. Model expected 1 layers, found 2 saved layers.
```

**Comment by Usrrrr** [comment]
I solved this issue by downgrading ~~both keras and~~ tensorflow.
Tensorflow version 2.15.0.post1
~~Keras version 2.15.0~~

From what I could gather the issue is caused by a mismatch of model architecture. I rolled back the version to the latest available when the commits were made for v0.3. 

A solution for this would be to specify the Tensorflow version in the requirements.txt.

Edit: Keras is version 2.15.0 by default, it does not need to be downgraded.

**Comment by Th3Tr1ckst3r** [comment]
As [Usrrrr](https://github.com/Usrrrr) mentioned, version downgrading as a solution actually checks out. 

So for those in the future that encounter this issue, the following code should resolve this issue:
```
pip3 uninstall tensorflow
pip3 install tensorflow==2.15.0.post1
```
Then, to valid it, you may also execute the following:
```
pip3 show tensorflow
```

**Comment by vasia1247** [comment]
@Usrrrr @Th3Tr1ckst3r Have you run the project under Windows? I have a problem specifically in the module for embed random messages (j-uniward-sim, hill, s-uniward, and so on). I compiled the jpeg_write.c and jpeg_read.c (.mex) files, copied them to the octave folder (aletheia/aletheia-cache/), registered actave in the Windows system environment (%Path%). While the script is running, aletheia calls octave, but nothing happens. The script runs without errors, but there are no output files with embedded messages. What to do? What could be the problem?

**Comment by daniellerch** [comment]
@vasia1247 Unfortunately, Alethia doesn’t work on Windows. Some adjustments need to be made, and I haven’t had time to do them.

**Comment by daniellerch** [comment]
Thanks, @Usrrrr! I’ve added the TensorFlow version to the requirements.txt file.
