### ISSUE TITLE
Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by RUSHIKESHWKAWALE** [daniellerch/aletheia#36]
![issue](https://github.com/daniellerch/aletheia/assets/141922769/9139439e-700e-4344-b43f-12578de6e141)
I am trying to run the steganalysis command in Ubuntu 20 on the VM.
And getting output an "Illegal instruction (core dumped)" error on the terminal on running the command "./aletheia.py auto sample_images/alaska2jpg".

**Comment by daniellerch** [comment]
I’m closing the issue as I can’t reproduce it.
