### ISSUE TITLE
How to use Xu-net to train model. Could you please give a command ?the data is .fea or raw image folder?

### ISSUE THREAD

**Issue by OrangeIUH** [daniellerch/aletheia#4]

**Comment by daniellerch** [comment]
The Xu-net implementation was replaced by SRNet, a state of the art Convolutional Neural Network for Steganalysis. 

An example command for training the network:
$ ./aletheia.py srnet experiment-boss-hill-0.4/trnset/cover/ experiment-boss-hill-0.4/trnset/stego/ sernet 0
