### ISSUE TITLE
my octave version is 4.2.2, when I run failed to load: liboctinterp.so.3: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by beibuwandeluori** [daniellerch/aletheia#5]

**Comment by beibuwandeluori** [comment]
when I run "python aletheia.py j-uniward-sim data/bossbaseJpeg75 0.40 data/bossbaseJpeg75_J_uniward-sim040/" to use j-uniward-sim ro embeding my jpeg image, and I get a bug in jpeg ./external/octave/jpeg_read.mex------failed to load: liboctinterp.so.3: cannot open shared object file: No such file or directory

**Comment by beibuwandeluori** [comment]
Now I have solved it. the solution as follow:
Firstly,You need to run 'cd  ./external/jpeg_toolbox', and then run 'make' to execute Makefile, so that you can get the new jpeg_read.mex and jpeg_write.mex in the 'external/octave/'. However,you may get a bug 'make: mkoctfile: Command not found' . and then you can run 'sudo apt-get install liboctave-dev', so that you can use the mkoctfile. Lastly,you need to run the 'make' to execute the Makefile again and you can deal with the problem.

**Comment by daniellerch** [comment]
Thanks for reporting.
I have improved the documentation.
