### ISSUE TITLE
other stego algorithm and polyglot?

### ISSUE THREAD

**Issue by pwneddesal** [daniellerch/aletheia#6]
Hi, can Aletheia detect other stego. algorithm i.e. polyglot, F5, DCT using The ATS attack?

**Comment by daniellerch** [comment]
The ATS attack works with F5 and other DCT based algorithms. Actually, the ATS attack works when the underlying ML-based algorithm can split images into cover and stego and when the second embedding is directional. You can find more information in this paper: https://arxiv.org/abs/1703.00796

W. r. t. polyglot, you can use other techniques designed for this purpose.
